version: '2'
services:
    gomongo:
        build: 
            context: ../
            dockerfile: docker/Dockerfile
        ports:
            - "80:8080"
        links:
            - mongodb
        restart: always
        container_name: gomongo
        environment:
            - MONGO_URL=mongodb://mongodb:27017
    mongodb:
        image: "mongo"
